// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fiqyafccamwqluunmara.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpcXlhZmNjYW13cWx1dW5tYXJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MjA1NDQsImV4cCI6MjA2MDI5NjU0NH0.tjUm-P0i2iB1Ewuiz8mc2JJEjaCF-wgE6kE2vkUucH8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);